const http=require('node:http');const fs=require('node:fs');const path=require('node:path');const {pathToFileURL}=require('node:url');const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const root=path.resolve(__dirname,'..')+'/';fs.mkdirSync(root+'test-artifacts',{recursive:true});const tools=await import(pathToFileURL(root+'src/booking-tools.js'));const worker=(await import(pathToFileURL(root+'src/customer-overlay.js'))).default;
assert.ok(Math.abs(tools.poolVolume({shape:'rectangle',unit:'metres',length:1,width:1,depth:1}).imperialGallons-219.969248299)<0.001);
assert.ok(Math.abs(tools.poolVolume({shape:'circle',unit:'metres',length:2,depth:1}).litres-Math.PI*1000)<0.001);
assert.throws(()=>tools.poolVolume({length:-1,width:2,depth:1}));
const originalFetch=global.fetch;global.fetch=async(url,opts)=>String(url).includes('/booking-preview')?Response.json({available:true,estimated_maximum_cents:25000,quote_required:false,window:'Oct 5–6',message:'This is a preliminary check. No booking or payment has been made.'}):originalFetch(url,opts);
const server=http.createServer(async(req,res)=>{try{let chunks=[];for await(const chunk of req)chunks.push(chunk);const data=Buffer.concat(chunks);const request=new Request('http://127.0.0.1:4173'+req.url,{method:req.method,headers:req.headers,...(req.method==='POST'?{body:data}: {})});const out=await worker.fetch(request,{},{});res.writeHead(out.status,Object.fromEntries(out.headers));res.end(Buffer.from(await out.arrayBuffer()));}catch(e){res.writeHead(500);res.end(String(e));}});await new Promise(r=>server.listen(4173,'127.0.0.1',r));
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});let errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const path of ['/','/haulers','/cisterns','/pools','/faq','/check-availability','/join','/demo/customer','/demo/hauler']){const response=await page.goto('http://127.0.0.1:4173'+path);assert.equal(response.status(),200,path);assert.ok((await page.locator('h1').count())>0,path);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile overflow '+path);}
await page.goto('http://127.0.0.1:4173/pools');await page.locator('[name=length]').fill('32');await page.locator('[name=width]').fill('16');await page.locator('[name=depth]').fill('5');assert.match(await page.locator('#pool-result').innerText(),/imperial gallons/);assert.match(await page.locator('#pool-result').innerText(),/6 loads/);await page.screenshot({path:root+'test-artifacts/pool-mobile.png',fullPage:true});
await page.goto('http://127.0.0.1:4173/check-availability');await page.locator('[name=address_line1]').fill('123 Test Road');await page.locator('[name=city]').fill('Pelham');await page.locator('[name=postal_code]').fill('L0S 1E0');await page.locator('#availability button').click();await page.getByText('Current coverage found').waitFor();assert.match(await page.locator('#coverage-result').innerText(),/250.00/);await page.screenshot({path:root+'test-artifacts/coverage-mobile.png',fullPage:true});
await page.goto('http://127.0.0.1:4173/');await page.screenshot({path:root+'test-artifacts/home-mobile.png',fullPage:true});await page.setViewportSize({width:1280,height:900});await page.goto('http://127.0.0.1:4173/haulers');await page.screenshot({path:root+'test-artifacts/haulers-desktop.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: calculator math, 9 routes, mobile layouts, quote form interaction, and browser script checks');await browser.close();await new Promise(r=>server.close(r));})().catch(e=>{console.error(e);process.exit(1)});
