export function poolVolume({shape='rectangle',unit='feet',length,width,depth}) {
  const values=[Number(length),Number(depth),...(shape==='circle'?[]:[Number(width)])];
  if(!values.every(v=>Number.isFinite(v)&&v>0)) throw new Error('Enter positive dimensions and the depth of water needed.');
  const scale=unit==='metres'?1:0.3048;
  const area=shape==='circle'?Math.PI*(Number(length)*scale/2)**2:Number(length)*Number(width)*scale**2*(shape==='oval'?Math.PI/4:1);
  const litres=area*Number(depth)*scale*1000;
  return {litres,imperialGallons:litres/4.54609};
}

function calculatorClient() {
  const form=document.getElementById('pool-calculator'); if(!form)return;
  const shape=form.elements.shape,unit=form.elements.unit,result=document.getElementById('pool-result');
  function update(){document.getElementById('pool-width-row').hidden=shape.value==='circle';document.getElementById('pool-length-label').textContent=shape.value==='circle'?'Diameter':'Length';try{const amount=poolVolume(Object.fromEntries(new FormData(form)));const loads=Math.ceil(amount.imperialGallons/Number(form.elements.load_size.value));result.textContent=Math.ceil(amount.imperialGallons).toLocaleString()+' imperial gallons (about '+Math.ceil(amount.litres).toLocaleString()+' litres). Approximately '+loads+' loads at '+Number(form.elements.load_size.value).toLocaleString()+' gallons per load.'}catch{result.textContent='Enter your pool dimensions to estimate the water needed.'}}
  form.addEventListener('input',update);shape.addEventListener('change',update);unit.addEventListener('change',update);update();
}

export function poolCalculator() {
  return `<section class="card"><h2>How much water does your pool need?</h2><p>For a full fill, use average water depth. For a top-up, use only the depth of water you need to add. All gallons shown are imperial.</p><form id="pool-calculator" onsubmit="return false"><div class="fields"><div><label>Pool shape<select name="shape"><option value="rectangle">Rectangular</option><option value="circle">Round</option><option value="oval">Oval</option></select></label></div><div><label>Dimensions in<select name="unit"><option value="feet">Feet</option><option value="metres">Metres</option></select></label></div><div><label><span id="pool-length-label">Length</span><input name="length" type="number" min="0.01" step="any" inputmode="decimal"></label></div><div id="pool-width-row"><label>Width<input name="width" type="number" min="0.01" step="any" inputmode="decimal"></label></div><div><label>Average water depth needed<input name="depth" type="number" min="0.01" step="any" inputmode="decimal"></label></div><div><label>Example load size<select name="load_size"><option value="2000">2,000 imperial gallons</option><option value="2500">2,500 imperial gallons</option><option value="3000" selected>3,000 imperial gallons</option></select></label></div></div><p id="pool-result" role="status" class="notice"></p><p class="muted">Approximate volume for regular shapes. Steps, slopes and irregular shapes change the amount. Load sizes are examples; available sizes depend on your address and hauler. Review the amount with your hauler before approving a pool quote.</p></form></section><script>const poolVolume=${poolVolume.toString()};(${calculatorClient.toString()})();</script>`;
}

function availabilityClient() {
  const form=document.getElementById('availability'),result=document.getElementById('coverage-result'),button=form.querySelector('button'),confirm=document.getElementById('confirm-address');
  form.addEventListener('input',()=>{confirm.hidden=true;form.elements.address_confirmed.checked=false});
  form.addEventListener('submit',async event=>{event.preventDefault();button.disabled=true;result.textContent='Checking the address, driving coverage and current rates…';const data=Object.fromEntries(new FormData(form));data.address_confirmed=form.elements.address_confirmed.checked;try{const response=await fetch('/api/availability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const info=await response.json();if(!response.ok)throw new Error(info.message||'The check is temporarily unavailable. Please try again.');result.replaceChildren();if(info.confirmation_required){for(const key of ['address_line1','city','postal_code'])if(info.address[key])form.elements[key].value=info.address[key];confirm.hidden=false;result.textContent=info.message+' '+(info.address.formatted_address||'');return;}confirm.hidden=true;const title=document.createElement('strong');title.textContent=info.available?'Current coverage found':'No published availability found';result.append(title,document.createElement('br'));if(info.available){const price=document.createElement('p');price.textContent=(info.quote_required?'Published-rate estimate: ':'Preliminary maximum: ')+new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(info.estimated_maximum_cents/100)+(info.quote_required?' — a hauler quote still needs your approval.':'.')+' Flexible window: '+info.window+'.';result.append(price);}result.append(document.createTextNode(info.message));}catch(error){result.textContent=error.message;}finally{button.disabled=false;}});
}

export function availabilityPage() {
  return `<main class="wrap content"><span class="pill">Niagara launch preparation</span><h1>Check coverage and pricing before signing up.</h1><p>See whether current hauler coverage and published rates match your address. Ordering is being prepared for launch. This check creates no account, booking or payment.</p><form class="card" id="availability"><div class="fields"><div class="field full"><label>Delivery street address<input name="address_line1" autocomplete="address-line1" maxlength="255" required></label></div><div><label>City<input name="city" autocomplete="address-level2" maxlength="120" required></label></div><div><label>Postal code<input name="postal_code" autocomplete="postal-code" maxlength="16" required></label></div><div><label>Water for<select name="order_type"><option value="cistern">Cistern</option><option value="pool">Pool</option><option value="hot_tub">Hot tub</option><option value="other">Other</option></select></label></div><div><label>Size per load (imperial gallons)<input type="number" name="load_size" min="100" max="30000" value="2000" required></label></div><div><label>Number of loads<input type="number" name="load_count" min="1" max="20" value="1" required></label></div><div><label>Hose distance needed (feet)<input type="number" name="hose_distance_feet" min="0" max="1000" value="24" required></label></div></div><label id="confirm-address" hidden><input type="checkbox" name="address_confirmed" style="width:auto;height:auto"> I confirm the suggested address above.</label><button class="btn" type="submit">Check availability</button><div id="coverage-result" class="notice" role="status" aria-live="polite">Prices vary by delivery amount, driving distance and hose requirements. Confirm the final price when ordering.</div></form><p><a class="btn" href="/join">Get launch updates</a> <a class="btn alt" href="/pools">Estimate pool water</a></p></main><script>(${availabilityClient.toString()})();</script>`;
}

export function faqBody() {
  const items=[
    ['Where will Water OnCall launch?','We are preparing our initial launch in Niagara, Ontario. Coverage depends on the available haulers, their approved stations, driving distance and truck capacity. Check your full delivery address before planning an order.'],
    ['How does pricing work?','Published prices include the delivery amount and applicable fuel, driving-distance and hose charges. For a standard cistern request, you review a maximum total before booking. Urgent, pool, hot tub and other requests need your approval of a hauler quote.'],
    ['When is my card charged?','A saved payment method is required to order. Payment is charged after a hauler accepts and any required price approval is complete. The accepted price stays attached to the booking; later unlisted charges need your approval.'],
    ['Can I keep my preferred water hauler?','Yes. Save your preferred hauler in your profile. If they do not accept, you choose whether to wait longer or use First Available. We do not switch you automatically.'],
    ['How soon can water arrive?','Flexible delivery normally starts in the next one or two business days, with the hauler confirming the date. Larger orders can take several days. Urgent requests depend on availability and do not guarantee immediate delivery.'],
    ['What are imperial gallons?','One imperial gallon is approximately 4.546 litres. Imperial gallons are different from US gallons. The pool calculator and delivery amounts on this website use imperial gallons.'],
    ['How are haulers approved?','Haulers apply for network review. Company approval, insurance, public-health or potable-water documentation, trucks and water stations are reviewed as part of setup. Check the delivery details provided for your booking.'],
    ['What if my delivery has a problem?','Follow the delivery in your account and report a problem within the displayed dispute window. Completed orders have a 72-hour review window before payout eligibility. Admin reviews reported problems and incomplete deliveries.'],
    ['Can I cancel an order?','Cancellation rules depend on the delivery stage and timing, and are shown during ordering. Once the hauler is On the Way, the full charge applies. Confirmed urgent orders are locked against customer cancellation.'],
    ['Can I order the same amount again?','Your account provides Order Again for completed deliveries. Review the address, amount, new delivery date and current price before submitting.']
  ];
  return `<main class="wrap content"><h1>Water delivery questions</h1><section class="card">${items.map(([q,a])=>`<details class="faq"><summary>${q}</summary><p>${a}</p></details>`).join('')}</section><a class="btn" href="/check-availability">Check your address</a> <a href="mailto:info@wateroncall.ca">Contact Water OnCall</a></main>`;
}
